### ISSUE TITLE
Init AC Network

### ISSUE THREAD

**Issue by Golly** [awjuliani/Meta-RL#2]
Hi, thank you for your code.

I have a issue with init AC Network for meta bandit: 
hidden = tf.concat(1, [self.prev_rewards, self.prev_actions_onehot, self.timestep])

It gave me a error:
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

Thank you very much for replay

**Comment by awjuliani** [comment]
Hi Golly,

That error is the result of the wrong argument order for tf.concat. In Tensorflow 1.0 they rearranged a number of the function arguments. It should be 

`tf.concat([self.prev_rewards, self.prev_actions_onehot, self.timestep],1)`

I just updated the three notebooks, and they should work correctly now.
